/**:
  ros__parameters:
    sensor_model: "InnovizTwoRaven"
    sensor_ip: "192.168.0.5"
    host_ip: "192.168.0.2"
    data_port: 9101
    frame_id: "innoviz"    
    setup_sensor: False
    online: True
