/**:
  ros__parameters:
    sensor_model: "InnoLidar" # See readme for supported models
    sensor_ip: "172.168.1.10" # Lidar Sensor IP
    host_ip: "172.168.1.101" # Broadcast IP from Sensor
    frame_id: "innovusion"
    data_port: 8010 # LiDAR Data Port
    setup_sensor: True
    online: True
